excelPathNotExist = "配置的excel文件夹路径不存在，请检查路径是否错误！"
excelFileIsLess = "excel文件个数小于两个，请增加过滤文件后再次运行！"
excelFileIsNotExist = "获取完文件路径与所有文件后，查找文件全路径不存在！"
excelSaveErro = "Excel表格的操作权限不足，请检查是否打开了对应的表格或无创建权限！"
excelSaveAgain = "在10秒后将再次尝试！如果再次失败请处理错误后在运行一次此工具！"
excelAddSheetParamErro = "代码错误！此处的sheet_list需要的是一个List传入！"